=== anmolverma1309/FSD_CSE15_anmolverma217/WEB Tech/exp5/tutorials.dtd
<!ELEMENT tutorials (tutorial)+>
<!ELEMENT tutorial (title, category , duration , instructor , fee)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT instructor (#PCDATA)>
<!ELEMENT fee (#PCDATA)>

=== anmolverma1309/FSD_CSE15_anmolverma217/WEB Tech/exp5/tutorials.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<?xml-stylesheet type = "text/css" href="style.css"?>
<!DOCTYPE tutorials SYSTEM "tutorials.dtd">
<tutorials>
    <tutorial>
        <title>Introduction to Python</title>
        <category>Programming</category>
        <duration>3 hours</duration>
        <instructor>John Doe</instructor>
        <fee>$2</fee>
    </tutorial>
    <tutorial>
        <title>Web Development </title>
        <category>Web Development</category>
        <duration>5 hours</duration>
        <instructor>Jane Smith</instructor>
        <fee>$7.5</fee>
    </tutorial>
    <tutorial>
        <title>DSA</title>
        <category>DSA</category>
        <duration>4 hours</duration>
        <instructor>Emily Johnson</instructor>
        <fee>$10000</fee>
    </tutorial>

  </tutorials>
